# This is a basic workflow that is manually triggered

name: Manually Update from Dev

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clonedev:
    if: github.repository == 'vt102/prod-website'
    runs-on: ubuntu-latest
    steps:
    - name: Github Sync
      uses: repo-sync/github-sync@v2.3.0
      with: 
        source_repo: "https://github.com/vt102/dev-website.git"
        source_branch: "main"
        destination_branch: "main"
        sync_tags: "true"
        github_token: ${{ secrets.PAT }}
